### ISSUE TITLE
Práctcia Validación de propuesta

### ISSUE THREAD

**Issue by Yabin-2021** [SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-bjny-huerto#2]
[Informe P1 - S1INSO.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-validacion-de-propuesta-de-valor-bjny-huerto/files/8136414/Informe.P1.-.S1INSO.pdf)

**Comment by IsraelNicolas61** [comment]
Calificación: 19%

**Comment by Yabin-2021** [comment]
https://drive.google.com/file/d/1_s-BcMzbPWJcv1YRSssjkVH7dvihoSjn/view?usp=sharing

Proyecto en Architect - Google Drive

**Comment by josealfredo79** [comment]
Bien hecho y revisado
